version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./docker/rabbit.definitions.json:/tmp/rabbit.definitions.json:ro
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/tmp/rabbit.definitions.json"

  hawk-collector:
    image: "hawk.collector"
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./.env.docker:/app/.env
    depends_on:
      - rabbitmq
