name: Update mono repository
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Mono repository update
        uses: peter-evans/repository-dispatch@v1
        env:
          REPOSITORY_MONO_PATH: collector
        with:
          token: ${{ secrets.HAWK_MONO_REPO_ACCESS_TOKEN }}
          event-type: submodule-changed
          repository: codex-team/hawk.mono
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "path": "${REPOSITORY_MONO_PATH}"}'
